Portfolio: setup and mobile first
Ferizad/Portfolio pull request #1
Opened 2023-02-15 14:25 UTC by Ferizad

The 2 sections you need to build for this project are the toolbar (or header), and the headline section. 
Use flexbox in all 2 sections.

2023-02-15 15:15 UTC, zieeco requested changes
Hi @Ferizad,


Great job! Kindly implement the suggested changes and your project is good to be approved 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 15:15 UTC, zieeco commented on README.md
> +
- Hey, great job with the readme, however, let's kindly remove this section since we've not added any questions users might want to ask concerning the project to make the readme more professional.

![Screenshot from 2023-02-15 15-30-50](https://user-images.githubusercontent.com/59397159/219056789-82b727ca-7510-46ac-8085-94040446a229.png)

2023-02-15 15:15 UTC, zieeco commented on README.md
> +
- Hey, since you've added the license, let's remove this placeholder text which tells how important it is to add a license file to make the readme more professional.

2023-02-15 15:15 UTC, zieeco commented on README.md
> +> Give credit to everyone who inspired your codebase.
- Hey, please, let's remove this placeholder text as it's there to guide you on how to add the appropriate contents to its section so therefore, it shouldn't be in the readme after you've updated it

2023-02-15 15:15 UTC, zieeco commented on README.md
> +> Describe how a new developer could make use of your project.
- Hey, please, let's remove this placeholder text as it's there to guide you on how to add the appropriate contents to its section so therefore, it shouldn't be in the readme after you've updated it

2023-02-15 15:15 UTC, zieeco commented on README.md
> +
- Hey, since you'd be updating the live demo link by adding one later in the course of building this project, please, make the link `coming soon` as you should not leave a broken link in the readme, or better still, remove this whole section then when you get to the milestone of deploying the project, you can therefore add this section again.

2023-02-15 15:15 UTC, zieeco commented on README.md
> +
- Hey, since you'd be updating the deployment using GitHub pages later in the course of building this project, please, kindly add `Using Github pages to deploy the website` to make it more descriptive.

2023-02-15 15:15 UTC, zieeco commented on README.md
> +
- Please, kindly remove this section as you've not added any test to the project.

2023-02-15 15:15 UTC, zieeco commented on README.md
> +
- Hey, you can add how to open the project from the terminal using the `code .` command to finish the description on how the users can have your project run locally on their machine.

2023-02-15 15:15 UTC, zieeco commented on index.html
> +    </section>
- Hey, please, kindly remove this section `<section class="homepage"></section>` as this is not a good way to use the section tag to improve your semantic usage. The header tag is a unique tag and shouldn't be wrapped in a section tag. it's a standalone tag.

2023-02-15 15:15 UTC, zieeco commented on index.html
> +            <h1 class="logo">Welcome</h1>
- Hey, please, kindly use a div in place of this h1 and wrap it in the `a` tag to make it a link, giving it the ability to be clickable as you want to ensure users can navigate from the homepage to other pages your website would have in the course of building the project.

2023-02-15 15:15 UTC, zieeco commented on index.html
> +            <img class="hamburger" src="media\Union.svg" alt="hamburger" width="20px" height="20px">
- Hey, also, you should not use inline styling in the HTML file as this is not considered a good practice. kindly remove the width and height you've added and style it using CSS.
- The hamburger should be wrapped in a `nav` tag as the `nav` tag contains the navigation content in the document to improve the web accessibility of your website. kindly add the nav tag.

2023-02-15 15:15 UTC, zieeco commented on index.html
> +              </picture>
- In order to add the background image for this section, please, kindly use the CSS background property to achieve this. Please, kindly remove the `<picture></picture>` and it contents totally from the document

2023-02-15 15:15 UTC, zieeco commented on index.html
> +              <div class="intro">
- Hey, for this container, kindly use the `section` tag as required as this is the first standalone section of your website, using the section would enforce the correct use of the html5 semantic tag. Also, `divs` is used to divide the different parts of your document and does not have any semantic meaning. please, kindly improve on this.

2023-02-16 05:42 UTC, AdnanOlarmmi reviewed
Hi @Ferizad, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Fixed most of previous reviewer's required changes.
- Nice one following the design's specifications.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 05:42 UTC, AdnanOlarmmi commented on README.md
> +
Nice one having the usage ending, but has the previous reviewer has stated, there should be detailed description on how the repo can be run on a local machine, to enable users access with effectively. follow [this](https://github.com/AdnanOlarmmi/Demo-Portfolio#usage) approach. 🙂

2023-02-16 05:42 UTC, AdnanOlarmmi commented on README.md
> +
Please, you can also follow the aforementioned approach for this section also 😀.

2023-02-16 05:42 UTC, AdnanOlarmmi commented on README.md
> +
Kindly 🙂 indicate what a user can use to deploy this project, as the previous reviewer has stated, 😀.
```
You can deploy this project using:
GitHub pages
```

2023-02-16 05:45 UTC, AdnanOlarmmi requested changes
Hi @Ferizad, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Fixed most of previous reviewer's required changes.
- Nice one following the design's specifications.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 05:45 UTC, AdnanOlarmmi commented on README.md
> +
Nice one having the usage ending, but has the previous reviewer has stated, there should be detailed description on how the repo can be run on a local machine, to enable users access with effectively. follow [this](https://github.com/AdnanOlarmmi/Demo-Portfolio#usage) approach. 🙂

2023-02-16 05:45 UTC, AdnanOlarmmi commented on README.md
> +To run tests, run the following command:
Please, you can also follow the aforementioned approach for this section also 😀.

2023-02-16 05:45 UTC, AdnanOlarmmi commented on README.md
> +You can deploy this project using:
Kindly 🙂 indicate what a user can use to deploy this project, as the previous reviewer has stated, 😀.
```
You can deploy this project using:
GitHub pages
```

2023-02-16 06:53 UTC, Shedrack-Sunday approved these changes
Hi @Ferizad 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)


# Highlights
- No linter errors ✔️
- Good implementations ✔️

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-18 15:01 UTC, merged