Portfolio: desktop version
Ferizad/Portfolio pull request #5
Opened 2023-02-23 13:55 UTC by Ferizad

✅Use media queries in your CSS file to make the desktop version look like the template selected (Desktop: >=768px).

✅In order to lay out the elements on the page use Grid and Flexbox.

2023-02-23 14:38 UTC, tufoinnkuo10 requested changes
Hi @Ferizad 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
- [ ] kindly remove the live demo section in your readme since you don't yet have a deployed version of your portfolio. 😄 

![tufoin](https://media.giphy.com/media/kc5SyOpKjxsZpEunsE/giphy.gif)

Optional suggestions
-[optional] kindly add information under the acknowledgment section of your readme. this will make your readme file more professional.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-02-23 14:38 UTC, tufoinnkuo10 commented on index.html
>              <p> I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded,
- [ ] great job. please kindly add the social icons on the headline section of the desktop version so it follows the figma design
yours
![Screenshot (823)_LI](https://user-images.githubusercontent.com/65298048/220934559-e9ebad95-9f5e-45e6-9016-7bdefda1987a.jpg)
figma
![Screenshot (824)_LI](https://user-images.githubusercontent.com/65298048/220934706-5dec4d1a-e17e-4359-882d-6e921cdb5bcb.jpg)

2023-02-23 14:38 UTC, tufoinnkuo10 commented on index.html
> +        </div>
- [ ] please kindly follow the design as much as possible.` my recent works` heading should appear like in the original design on the desktop version
yours
![Screenshot (822)_LI](https://user-images.githubusercontent.com/65298048/220936423-4b0db12d-63dd-4960-8d6d-0bac12cab961.jpg)
figma
![Screenshot (821)](https://user-images.githubusercontent.com/65298048/220936468-417048fb-8b49-4977-89ee-219445564e96.png)

2023-02-23 14:38 UTC, tufoinnkuo10 commented on index.html
> +<h1 class="mail">myemailhere@email.com</h1>
- [ ] great job with the contact section. please kindly align the text and the form to align with the cards above it like in the original version. nice work
yours
![Screenshot (825)_LI](https://user-images.githubusercontent.com/65298048/220935335-0015b0dc-5fef-43ec-b562-ad9045c1c32d.jpg)
figma
![Screenshot (826)](https://user-images.githubusercontent.com/65298048/220935578-37d64dd7-2fde-4fe0-8b28-28a4b9c93bf3.png)

2023-02-23 16:10 UTC, divinecharlotte requested changes
# Hello @Ferizad      👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- GitHub Flow observed ✔️
- Good commit messages ✔️
- Descriptive Readme 👍 
## Required Changes ♻️
consider the comments under the codes

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 16:10 UTC, divinecharlotte commented on index.html
>              <p> I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded,
- [ ] kindly consider adding everything in this section in the center of the background image and also consider removing the overflow -x so as your website won't be scrolling to the left and right this will help you to implement well the Figma design
- 
![yyy](https://user-images.githubusercontent.com/60146030/220959902-c72dba8e-7bf0-4c26-9acf-c1e91b840af4.PNG)

2023-02-23 16:10 UTC, divinecharlotte commented on index.html
>                  <input class="input1" maxlength="30" type="text" placeholder="Full name" id="name" value=""
- [ ] I can see you implemented the requested change by the previous reviewer but there is a small thing that is missing you were almost there check on the image below
- 
![as](https://user-images.githubusercontent.com/60146030/220963987-5fa50503-d903-46e0-8245-2fb2df11dc4e.PNG)

consider aligning this text to the cards above it as requested above try to make them have the same margin you can do so by decreasing the font size you are giving the text and reduce the margin

2023-02-24 05:37 UTC, shella12 requested changes
Hi @Ferizad , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Fixed headline section margins ✅ 
- Fixed "My recent Works" heading ✅   

 ## Required Changes ♻️

- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 05:37 UTC, shella12 commented on index.html
> +
- [ ] As suggested by previous reviewers please align your skill frames with contact us card like that of in the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=s8WLg64fDsS6M8eZ-0)

#### **_Figma Design_**

<img width="733" alt="Screenshot 2023-02-24 at 10 09 19 AM" src="https://user-images.githubusercontent.com/44798044/221100204-f5ed624e-fffb-4607-8844-a134794533d8.png">

#### _**Your Design**_

<img width="1501" alt="Screenshot 2023-02-24 at 10 10 01 AM" src="https://user-images.githubusercontent.com/44798044/221100233-fbd4f5af-5019-4dff-acf6-594dfdf15ae3.png">

2023-02-24 06:30 UTC, huseyinbiyik approved these changes
Hi @Ferizad,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
- Please rename your project with the project name instead of the Readme template. In this way, your repository will look more professional 👍 
<img width="1077" alt="Screenshot 2023-02-24 at 9 27 17 AM" src="https://user-images.githubusercontent.com/25887253/221108136-29659eec-0bce-436e-94f1-89a325ad7128.png">
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Add style"

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 06:47 UTC, merged